export const textBiometrics = {
    "FaceTec_accessibility_cancel_button": "Cancelar",

    "FaceTec_feedback_center_face": "Centra tu cara",
    "FaceTec_feedback_face_not_found": "Coloca tu cara dentro del marco",
    "FaceTec_feedback_move_phone_away": "Muévete para atrás",
    "FaceTec_feedback_move_away_web": "Muévete para atrás",
    "FaceTec_feedback_move_phone_closer": "Acercate más",
    "FaceTec_feedback_move_phone_to_eye_level": "Acerca el teléfono al nivel de los ojos",
    "FaceTec_feedback_move_to_eye_level_web": "Mira fijamente hacia la cámara",
    "FaceTec_feedback_face_not_looking_straight_ahead": "Mira para enfrente",
    "FaceTec_feedback_face_not_upright": "Mantén la cabeza recta",
    "FaceTec_feedback_face_not_upright_mobile": "Mantén la cabeza recta",
    "FaceTec_feedback_hold_steady": "No te muevas",
    "FaceTec_feedback_move_web_closer": "Mueva la cara más cerca y rellene el óvalo",
    "FaceTec_feedback_move_web_even_closer": "Muévete más cerca",
    "FaceTec_feedback_use_even_lighting": "Ilumina tu rostro de manera más uniforme",

    "FaceTec_instructions_header_ready_desktop": "Prepárate para tu video selfie",
    "FaceTec_instructions_header_ready_1_mobile": "Prepárate para",
    "FaceTec_instructions_header_ready_2_mobile": "Tu video selfie",
    "FaceTec_instructions_message_ready_desktop": "Enmarca tu rostro en el óvalo, presiona Estoy listo y acércate",
    "FaceTec_instructions_message_ready_1_mobile": "Enmarca tu rostro en el óvalo,",
    "FaceTec_instructions_message_ready_2_mobile": "Presiona Estoy listo y muévete más cerca",

    "FaceTec_action_im_ready": "Estoy listo",
    "FaceTec_presession_frame_your_face": "Enmarca tu cara en el óvalo",
    "FaceTec_presession_look_straight_ahead": "Mira hacia adelante",
    "FaceTec_presession_hold_steady3": "Mantente firme durante: 3",
    "FaceTec_presession_hold_steady2": "Mantente firme durante: 2",
    "FaceTec_presession_hold_steady1": "Mantente firme durante: 1",
    "FaceTec_presession_eyes_straight_ahead": "Mira hacia adelante",
    "FaceTec_presession_remove_dark_glasses": "Eliminar gafas oscuras",
    "FaceTec_presession_neutral_expression": "Expresión neutral, sin sonreír",
    "FaceTec_presession_conditions_too_bright": "Lugar demasiado brillante",
    "FaceTec_presession_brighten_your_environment": "Ilumina tu entorno",

    "FaceTec_result_facescan_upload_message": "Subiendo escaneo facial 3D<br/>Encriptado<br/>",
    "FaceTec_result_idscan_upload_message": "Subiendo Documento <br/>Encriptado<br/>",

    "FaceTec_retry_header": "Intentémoslo de nuevo",
    "FaceTec_retry_subheader_message": "Necesitamos una selfie de video más clara",
    "FaceTec_retry_your_image_label": "Tu selfie",
    "FaceTec_retry_ideal_image_label": "Postura Ideal",
    "FaceTec_retry_instruction_message_1": "No utilice deslumbramiento o iluminación extrema.",
    "FaceTec_retry_instruction_message_2": "Expresión neutral, sin sonreír",
    "FaceTec_retry_instruction_message_3": "Imagen demasiado borrosa, limpia tu cámara",
    "FaceTec_action_try_again": "Intenta de nuevo",

    "FaceTec_camera_feed_issue_header": "Problema con el cifrado de la transmisión de la cámara",
    "FaceTec_camera_feed_issue_subheader_message": "Este sistema no se puede verificar debido a lo siguiente:",
    "FaceTec_camera_feed_issue_table_header_1": "Posible problema",
    "FaceTec_camera_feed_issue_table_header_2": "Arreglar",
    "FaceTec_camera_feed_issue_table_row_1_cell_1_firefox_permissions_error": "Los permisos de la cámara no están activados en Firefox.",
    "FaceTec_camera_feed_issue_table_row_1_cell_2_firefox_permissions_error": "Comprobar permisos activos.",
    "FaceTec_camera_feed_issue_table_row_1_cell_1": "La cámara ya está en uso por otra aplicación.",
    "FaceTec_camera_feed_issue_table_row_1_cell_2": "Cierra la otra aplicación.",
    "FaceTec_camera_feed_issue_table_row_2_cell_1": "Una aplicación de terceros está modificando el video.",
    "FaceTec_camera_feed_issue_table_row_2_cell_2": "Cerrar/Desinstalar la otra aplicación.",
    "FaceTec_camera_feed_issue_table_row_3_cell_1": "El dispositivo no se puede asegurar.",
    "FaceTec_camera_feed_issue_table_row_3_cell_2": "Usa un dispositivo diferente.",
    "FaceTec_camera_feed_issue_subtable_message": "Esta aplicación bloquea configuraciones sospechosas de cámaras web. <a href='https://livenesscheckhelp.com/' target='_blank' style='text-decoration:underline; pointer-events:all;'>Más información aquí</a>.",
    "FaceTec_camera_feed_issue_action": "INTENTAR DE NUEVO DE TODOS MODOS",
    "FaceTec_camera_feed_issue_action_firefox_permissions_error": "OK",

    "FaceTec_camera_permission_header": "Habilitar cámara",
    "FaceTec_camera_permission_message": "Los permisos de la cámara están deshabilitados.<br/>Compruebe la configuración de su sistema operativo y navegador.",
    "FaceTec_action_ok": "OK",

    "FaceTec_enter_fullscreen_header": "Modo Selfie a pantalla completa",
    "FaceTec_enter_fullscreen_message": "Antes de comenzar, haga clic en el botón a continuación para abrir el modo de pantalla completa.",
    "FaceTec_enter_fullscreen_action": "ABRE PANTALLA COMPLETA",

    "FaceTec_initializing_camera": "Cifrado de la transmisión de la cámara...",
    "FaceTec_initializing_camera_still_loading": "Cifrado de la transmisión de la cámara...",

    "FaceTec_idscan_type_selection_header": " Prepárese para escanear<br/>su documento de identidad",
    "FaceTec_action_continue": "CONTINUAR",
    "FaceTec_idscan_capture_id_front_instruction_message": "Mostrar el frente de la identificación",
    "FaceTec_idscan_capture_id_back_instruction_message": "Mostrar el reverso de la identificación",
    "FaceTec_action_take_photo": "TOMAR FOTO",
    "FaceTec_idscan_review_id_front_instruction_message": "Confirme que la foto es clara y legible",
    "FaceTec_idscan_review_id_back_instruction_message": "Confirme que la foto es clara y legible",
    "FaceTec_action_accept_photo": "ACEPTAR",
    "FaceTec_action_retake_photo": "RETOMAR",
    "FaceTec_idscan_ocr_confirmation_main_header": "Revisar y confirmar",
    "FaceTec_action_confirm": "CONFIRMAR INFORMACIÓN",

    "FaceTec_result_idscan_unsuccess_message": "Foto de identificación<br/>No coincide<br> con el rostro del usuario",

    "FaceTec_result_idscan_success_front_side_message": "Tu rostro 3D<br/>coincide con tu identificación",
    "FaceTec_result_idscan_success_front_side_back_next_message": "Tu rostro 3D<br/>coincide con tu identificación",
    "FaceTec_result_idscan_success_back_side_message": "Parte posterior de la identificación<br/>Capturada",
    "FaceTec_result_idscan_success_user_confirmation_message": "Verificación de identificación <br/> Completa",
    "FaceTec_result_idscan_retry_face_did_not_match_message": "La cara no coincidía<br/>lo suficiente",
    "FaceTec_result_idscan_retry_id_not_fully_visible_message": "El documento de identidad<br/>no se ve completamente",
    "FaceTec_result_idscan_retry_ocr_results_not_good_enough_message": "El Texto de la identificación no es legible",
    "FaceTec_result_idscan_retry_id_type_not_suppported_message": "Tipo de identificación no compatible<br/>Utilice una identificación diferente",

    "FaceTec_result_success_message": "Éxito!"
}